/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Random;

public class App {
    public static void main(String[] args) {
        Random aleatorio = new Random();
        int numero = aleatorio.nextInt()
    }
}
