/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Personagem jogador1 = new Personagem();

        IO.println(jogador1.obterVida());

        jogador1.reduzirVida(2);

        IO.println(jogador1.obterVida());

        jogador1.restaurarVida(1);

        IO.println(jogador1.obterVida());

        jogador1.restaurarVida(3);

        IO.println(jogador1.obterVida());

        jogador1.definirVidaMax(5);

        IO.println(jogador1.obterVida());

        jogador1.restaurarVida(2);

        IO.println(jogador1.obterVida());
    }
}
