/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        int dia = Integer.parseInt(IO.readln("Entre com o dia: "));
        String mes = IO.readln("Entre com o mês: ").toLowerCase();
        String estacao;
        switch (mes){
            case "janeiro","fevereiro" -> estacao = "Verão";
            case "abril", "maio" -> estacao = "Outono";
            case "julho", "agosto" -> estacao ="Inverno";
            case "outubro", "novembro" -> estacao ="Primavera";
            case "março" -> estacao = (dia >= 20) ? "Outono" : "Verão";
            case "junho" -> estacao = (dia >= 21) ? "Inverno" : "Outono";
            case "setembro" -> estacao = (dia >= 22) ? "Primavera" : "Inverno";
            case "dezembro" -> estacao = (dia >= 21) ? "Verão" : "Primavera";
            default -> estacao = "ERRO: mês invalido";
        }
        IO.println(estacao);

    }
}
