/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
       String formato = args[0];
       int dimensao = Integer.parseInt(args[1]);
       if (formato.equals("triangulo")){
           for (int i = 0; i <= dimensao; i++) {
               for (int j = 0; j < i; j++) {
                   IO.print("*");
               }
               IO.println();
           }
       } else if (formato.equals("losango")) {
           int tamanho;
           if (dimensao % 2 != 0){
               tamanho = 1;
           } else {
               tamanho = 0;
           }
           int meio = dimensao/2;
           for (int i = 1; i <= dimensao; i++) {
               int espacamento = (dimensao - tamanho) / 2;
               for (int j = 0; j <= espacamento; j++) {
                   IO.print(" ");
               }
               IO.println("*".repeat(tamanho));
               if (i <= meio){
                   tamanho += 2;
               } else {
                   tamanho -=2;
               }
               IO.println();
           }
       } else if (formato.equals("retangulo")) {
           int largura = Integer.parseInt(args[2]);
           for (int i = 1; i <= largura; i++) {
               for (int j = 1; j <= dimensao; j++) {
                   if (i == 1 || i == largura){
                       IO.print("*");
                   } else {
                       if (j == 1 || j == dimensao){
                           IO.print("*");
                       }else {
                           IO.print(" ");
                       }
                   }

               }
               IO.println();
           }
       }
    }
}
