/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Random;

public class App {
    public static void main(String[] args) {
        String[][] matriz = new String[9][9];
        for (int i = 0; i < 10; i++) {
            int colunaAleatoria = (new Random()).nextInt(10);
            int linhaAleatoria = (new Random()).nextInt(10);
            matriz[linhaAleatoria][colunaAleatoria] = "*";
        }
        for (int i = 0; i < matriz.length; i++) {
            IO.println();
        }
    }
}
